// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "mostlikelyto/src/domain"
import mock "github.com/stretchr/testify/mock"

// QuestionRepository is an autogenerated mock type for the QuestionRepository type
type QuestionRepository struct {
	mock.Mock
}

// FindAll provides a mock function with given fields:
func (_m *QuestionRepository) FindAll() ([]domain.Question, error) {
	ret := _m.Called()

	var r0 []domain.Question
	if rf, ok := ret.Get(0).(func() []domain.Question); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Question)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
